#!/usr/bin/env python3
"""Extract Hinglish vocabulary from ALL videos on the user's source YouTube channel.

Uses YouTube Data API to enumerate videos, then youtube-transcript-api to
fetch each video's captions (auto-generated by YouTube). This avoids
yt-dlp bot-detection issues on GitHub Actions runners.

Captions are usually in Hindi (Devanagari) for Hindi-spoken videos. For
gaps where captions are unavailable or English-only, we still skip cleanly.

Workflow:
  1. List all videos from CHANNEL_ID_2 via YouTube Data API (uploads playlist)
  2. Cap at MAX_VIDEOS most recent
  3. youtube-transcript-api fetches each video's caption track (Hindi preferred)
  4. Aggregate transcripts, extract Devanagari + Latin words
  5. Compare against current map values + EXPECTED_ENGLISH allowlist
  6. Output gap lists for human review

Outputs:
  - transcripts/transcript_<videoid>.txt    full per-video text
  - vocab_analysis.json                     gap analysis with frequencies
  - videos.json                             list of videos processed
"""

from __future__ import annotations

import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

import requests

OPENAI_KEY = os.environ.get("OPENAI_API_KEY", "")  # unused now but kept for future
YT_API_KEY = os.environ["YOUTUBE_API_KEY_1"]
CHANNEL_ID = os.environ["CHANNEL_ID_2"]
MAX_VIDEOS = int(os.environ.get("MAX_VIDEOS", "9999"))

WORK = Path("/tmp/vocab")
WORK.mkdir(exist_ok=True)
ARTIFACT_DIR = Path("transcripts")
ARTIFACT_DIR.mkdir(exist_ok=True)


def load_current_map() -> dict:
    src = open("daily_short.py").read()
    s = src.index(
        "# ╔══════════════════════════════════════════════════════════════════════╗\n"
        "# ║                   TTS PRE-PROCESSING"
    )
    e = src.index("def sarvam_tts_to_mp3")
    ns: dict = {}
    exec(src[s:e], ns)
    return ns["_TTS_HINGLISH_DEVANAGARI"]


def load_expected_english() -> set:
    src = open(".github/qa_loop.py").read()
    s = src.index("EXPECTED_ENGLISH = {")
    e = src.index("}", s) + 1
    ns: dict = {}
    exec(src[s:e], ns)
    return ns["EXPECTED_ENGLISH"]


def get_uploads_playlist_id(channel_id: str) -> str:
    r = requests.get(
        "https://www.googleapis.com/youtube/v3/channels",
        params={"part": "contentDetails", "id": channel_id, "key": YT_API_KEY},
        timeout=30,
    )
    r.raise_for_status()
    items = r.json().get("items", [])
    if not items:
        raise RuntimeError(f"No channel found for id={channel_id}")
    return items[0]["contentDetails"]["relatedPlaylists"]["uploads"]


def list_videos(playlist_id: str, max_videos: int) -> list:
    videos = []
    page_token = None
    while len(videos) < max_videos:
        r = requests.get(
            "https://www.googleapis.com/youtube/v3/playlistItems",
            params={
                "part": "snippet,contentDetails",
                "playlistId": playlist_id,
                "maxResults": min(50, max_videos - len(videos)),
                "pageToken": page_token,
                "key": YT_API_KEY,
            },
            timeout=30,
        )
        r.raise_for_status()
        data = r.json()
        for item in data.get("items", []):
            videos.append({
                "video_id": item["contentDetails"]["videoId"],
                "title": item["snippet"]["title"],
                "published_at": item["snippet"]["publishedAt"],
            })
        page_token = data.get("nextPageToken")
        if not page_token:
            break
    return videos[:max_videos]


def fetch_transcript(video_id: str) -> str | None:
    """Fetch caption text for a video via youtube-transcript-api.
    Tries Hindi first (better for Devanagari), falls back to English."""
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
    except ImportError:
        print("    !! youtube-transcript-api not installed", flush=True)
        return None

    # Try the modern instance API first; fall back to legacy classmethod.
    entries = None
    last_err = None
    for langs in (["hi", "hi-IN", "en", "en-IN"], ["en", "en-IN"], ["hi"]):
        try:
            # New API (>= 1.0): instance method .fetch()
            api = YouTubeTranscriptApi()
            fetched = api.fetch(video_id, languages=langs)
            entries = fetched.to_raw_data() if hasattr(fetched, "to_raw_data") else list(fetched)
            break
        except Exception as e1:
            last_err = e1
            try:
                # Legacy API: classmethod .get_transcript()
                entries = YouTubeTranscriptApi.get_transcript(video_id, languages=langs)
                break
            except Exception as e2:
                last_err = e2
                continue

    if not entries:
        if last_err:
            print(f"    !! transcript fetch failed: {str(last_err)[:120]}", flush=True)
        return None

    # entries is a list of {text, start, duration}
    text = " ".join(e.get("text", "") for e in entries if e.get("text"))
    return text.strip() or None


def main() -> int:
    current_map = load_current_map()
    expected_english = load_expected_english()
    mapped_devanagari = set(current_map.values())
    mapped_latin_keys = set(current_map.keys())

    print(f"Current map: {len(current_map)} entries", flush=True)
    print(f"EXPECTED_ENGLISH: {len(expected_english)} entries", flush=True)

    print(f"\nFetching uploads playlist for channel {CHANNEL_ID}...", flush=True)
    uploads_id = get_uploads_playlist_id(CHANNEL_ID)
    videos = list_videos(uploads_id, MAX_VIDEOS)
    print(f"Found {len(videos)} videos to process (cap={MAX_VIDEOS})", flush=True)

    Path("videos.json").write_text(json.dumps(videos, ensure_ascii=False, indent=2))

    all_transcripts = []
    skipped = 0

    for i, v in enumerate(videos, 1):
        vid = v["video_id"]
        title_short = v['title'][:60]
        text = fetch_transcript(vid)
        if not text:
            print(f"[{i}/{len(videos)}] {vid}  SKIP — no transcript", flush=True)
            skipped += 1
            continue

        all_transcripts.append({
            "video_id": vid,
            "title": v["title"],
            "transcript": text,
        })
        (ARTIFACT_DIR / f"transcript_{vid}.txt").write_text(text, encoding="utf-8")
        print(f"[{i}/{len(videos)}] {vid}  ✅ {len(text):>6} chars  — {title_short}", flush=True)

    # ── Aggregate ──
    all_text = " ".join(t["transcript"] for t in all_transcripts)
    devanagari_words = re.findall(r"[\u0900-\u097F][\u0900-\u097F\u200d]*", all_text)
    latin_words = [w.lower() for w in re.findall(r"[a-zA-Z][a-zA-Z'-]*", all_text)]

    deva_freq = Counter(devanagari_words)
    latin_freq = Counter(latin_words)

    deva_gap = {w: c for w, c in deva_freq.items() if w not in mapped_devanagari}
    latin_gap = {
        w: c for w, c in latin_freq.items()
        if w not in expected_english
        and w not in mapped_latin_keys
        and not w.isdigit()
        and len(w) > 1
    }

    analysis = {
        "channel_id": CHANNEL_ID,
        "videos_attempted": len(videos),
        "videos_succeeded": len(all_transcripts),
        "videos_skipped_no_transcript": skipped,
        "total_chars_transcribed": sum(len(t["transcript"]) for t in all_transcripts),
        "devanagari_words_total": len(devanagari_words),
        "devanagari_unique": len(deva_freq),
        "devanagari_already_mapped_count": sum(1 for w in deva_freq if w in mapped_devanagari),
        "devanagari_gaps_count": len(deva_gap),
        "devanagari_TOP_GAPS": [
            {"word": w, "count": c}
            for w, c in sorted(deva_gap.items(), key=lambda x: -x[1])[:1000]
        ],
        "latin_words_total": len(latin_words),
        "latin_unique": len(latin_freq),
        "latin_gaps_count": len(latin_gap),
        "latin_TOP_GAPS": [
            {"word": w, "count": c}
            for w, c in sorted(latin_gap.items(), key=lambda x: -x[1])[:1000]
        ],
    }

    Path("vocab_analysis.json").write_text(
        json.dumps(analysis, ensure_ascii=False, indent=2)
    )

    print("\n" + "=" * 70)
    print("SUMMARY")
    print(f"  Videos: {analysis['videos_succeeded']}/{analysis['videos_attempted']}"
          f" (skipped {skipped})")
    print(f"  Total chars: {analysis['total_chars_transcribed']:,}")
    print(f"  Devanagari unique: {analysis['devanagari_unique']:,}")
    print(f"    Already mapped : {analysis['devanagari_already_mapped_count']:,}")
    print(f"    GAPS           : {analysis['devanagari_gaps_count']:,}")
    print(f"  Latin unique: {analysis['latin_unique']:,}")
    print(f"    GAPS           : {analysis['latin_gaps_count']:,}")
    print(f"\nTop 50 Devanagari gaps:")
    for g in analysis["devanagari_TOP_GAPS"][:50]:
        print(f"  [{g['count']:>4}]  {g['word']}")
    print(f"\nTop 50 Latin gaps:")
    for g in analysis["latin_TOP_GAPS"][:50]:
        print(f"  [{g['count']:>4}]  {g['word']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
